### ISSUE TITLE
Illegal Move Error [Solved]

### ISSUE THREAD

**Issue by ravihammond** [facebookresearch/off-belief-learning#4]
While attempting to run `obl1.sh` and the other training scripts, the program would _always_ crash, giving me an illegal move error at the beginning of training. After implementing the solution from another issue [described here](https://github.com/facebookresearch/hanabi_SAD/issues/20#issuecomment-821570517), the script finally started working, but after a few hours, another illegal move would occur. 

My software and hardware setup [is described here](https://github.com/facebookresearch/off-belief-learning/issues/3).

After some investigation, I identified the cause of the problem and solved the issue. My experiments showed that there was an approximately 1/1000000 chance when calling [torch.multinomial()](https://pytorch.org/docs/stable/generated/torch.multinomial.html), that it will sample an element with zero weight - which should never happen. [Here is a post](https://github.com/pytorch/pytorch/issues/13867) where somebody else has experienced the same issue. The problem was [eventually fixed](https://github.com/pytorch/pytorch/pull/16075) in newer versions of Pytorch, but the version I'm using still has the same issue.

To fix the problem, I edited the `act()` function in the `r2d2.py` file to check for an illegal action, and re-sample a new one. I put this code inside a loop to cover the exceptionally rare case of more than one illegal action being sampled in a row.

Here is the fixed `act()` function I'm using in my code. The program now runs without any illegal action errors.

```python
@torch.jit.script_method
def act(self, obs: Dict[str, torch.Tensor]) -> Dict[str, torch.Tensor]:
    """
    Acts on the given obs, with eps-greedy policy.
    output: {'a' : actions}, a long Tensor of shape
        [batchsize] or [batchsize, num_player]
    """
    priv_s = obs["priv_s"]
    publ_s = obs["publ_s"]
    legal_move = obs["legal_move"]

    if "eps" in obs:
        eps = obs["eps"].flatten(0, 1)
    else:
        eps = torch.zeros((priv_s.size(0),), device=priv_s.device)

    if self.vdn:
        bsize, num_player = obs["priv_s"].size()[:2]
        priv_s = obs["priv_s"].flatten(0, 1)
        publ_s = obs["publ_s"].flatten(0, 1)
        legal_move = obs["legal_move"].flatten(0, 1)
    else:
        bsize, num_player = obs["priv_s"].size()[0], 1

    hid = {"h0": obs["h0"], "c0": obs["c0"]}

    if self.boltzmann:
        temp = obs["temperature"].flatten(0, 1)
        greedy_action, new_hid, prob = self.boltzmann_act(
            priv_s, publ_s, legal_move, temp, hid
        )
        reply = {"prob": prob}
    else:
        greedy_action, new_hid = self.greedy_act(priv_s, publ_s, legal_move, hid)
        reply = {}

    random_action = legal_move.multinomial(1).squeeze(1)

    # Re-sample random action if action is illegal
    while True:
        legal_size = torch.prod(torch.tensor(legal_move.shape))
        ascending = torch.arange(0, legal_size, legal_move.shape[1], device=random_action.device)
        take_indices = random_action + ascending
        take_result = torch.take(legal_move, take_indices)
        illegal_action_selected = torch.any(take_result == 0)
        
        if not illegal_action_selected:
            break

        random_action = legal_move.multinomial(1).squeeze(1)
    
    rand = torch.rand(greedy_action.size(), device=greedy_action.device, dtype=torch.double)

    if self.greedy:
        action = greedy_action
    else:
        assert rand.size() == eps.size()
        # Use fix from https://github.com/facebookresearch/hanabi_SAD/issues/20
        action = torch.where(rand < eps, random_action, greedy_action).detach()

    if self.vdn:
        action = action.view(bsize, num_player)
        greedy_action = greedy_action.view(bsize, num_player)
        rand = rand.view(bsize, num_player)

    reply["a"] = action.detach().cpu()
    reply["h0"] = new_hid["h0"].detach().cpu()
    reply["c0"] = new_hid["c0"].detach().cpu()

    size = torch.prod(torch.tensor(legal_move.shape))
    ascending = torch.arange(0, size, legal_move.shape[1])
    take_indices = reply["a"] + ascending
    selected_action = torch.take(legal_move.detach().cpu(), take_indices)

    # If an illegal action get's selected, kill the progrom.
    if torch.any(selected_action == 0) == 1:
        raise Exception("Found illegal action")

    return reply
```

**Comment by hengyuan-hu** [comment]
Thanks for flagging this. This should be automatically resolved since we can now run on the latest pytorch.
