### ISSUE TITLE
Sending v0-belief to python frontend

### ISSUE THREAD

**Issue by PeppaCat** [facebookresearch/off-belief-learning#6]
Hi, Hengyuan. Thanks for the great repo! I wonder if it possible to send the v0-belief (`float vector`) to python frontend interface [here](https://github.com/facebookresearch/off-belief-learning/blob/6c909bf2f3ce0837010711e3c2812954fb3ed6e6/hanabi-learning-environment/pyhanabi.py#L965):
```
#pyhanabi.py
c_encoding_str = lib.EncodeObservation(self._encoder,
                                       observation.observation())
```
which is generated from [here](https://github.com/facebookresearch/off-belief-learning/blob/6c909bf2f3ce0837010711e3c2812954fb3ed6e6/hanabi-learning-environment/pyhanabi.cc#L839)
```
#pyhanabi.CC
char* EncodeObservation(pyhanabi_observation_encoder_t* encoder,
                        pyhanabi_observation_t* observation) {
  REQUIRE(encoder != nullptr);
  REQUIRE(encoder->encoder != nullptr);
  REQUIRE(observation != nullptr);
  REQUIRE(observation->observation != nullptr);
  return nullptr;
}
```

The original binary representation (0 or 1) can be easily encapsulated as a string stream (as done in the vanilla HLE). I wonder what might be a good choice for floats here (maybe truncating them might be inaccurate)? An temporary solution I come out is to send required statistics to the python frontend and done v0-belief calculation there.

**Comment by hengyuan-hu** [comment]
You can use the pybind library as used in this repo.
https://github.com/facebookresearch/off-belief-learning/blob/6c909bf2f3ce0837010711e3c2812954fb3ed6e6/rlcc/pybind.cc#L293

I found it much easier to use than the original python/c++ interface of the
hanabi learning environment. You can bind anything you want and not
worrying about type encoding/decoding.
