### ISSUE TITLE
Any suggestions for the hyperparameter aux_weight

### ISSUE THREAD

**Issue by PaladinEE15** [facebookresearch/off-belief-learning#9]
Hi Hengyuan,

There is a hyperparameter aux_weight in selfplay.py, and I guess that it indicates the weight of the auxiliary task loss term. However, I cannot find the recommended value for it. Any Suggestions?

Sincerely,
PaladinEE15

**Comment by hengyuan-hu** [comment]
Depending on what you want. If your goal is to maximize the selfplay
performance, the AUX is not necessary, i.e. 0 may work quite well. If you
want to maximize cross-play scores over several seeds, then >= 0.25 is
good. We use 0.25 in most experiments when AUX is involved.

**Comment by PaladinEE15** [comment]
Thanks for your suggestions
